name: Publish to Wiki
on:
  push:
    branches:
      - main

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Wiki
        uses: ./
        with:
          docs-folder: 'docs'
          github-token: ${{ secrets.GITHUB_TOKEN }} 